name: CI

on:
  push:
    branches:
      - master
  pull_request:
  # schedule:
  #   - cron: 3 0 * * *  # Run daily at 0:03 UTC

jobs:
  pep8-tests:
    name: PEP-8
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os:
          - ubuntu-16.04
        runner-python-version:
          - 3.8
    steps:

      - name: Check out ${{ github.repository }} on disk
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.runner-python-version }}

      - name: Set up pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tests/sanity/requirements.txt') }}-${{ hashFiles('tests/unit/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install test requirements
        run: python -m pip install -Ur test-requirements.txt

      - name: Run PEP8 tests
        run: tox

  pylint-tests:
    name: Pylint
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os:
          - ubuntu-16.04
        runner-python-version:
          - 3.8
    steps:

      - name: Check out ${{ github.repository }} on disk
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.runner-python-version }}

      - name: Set up pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tests/sanity/requirements.txt') }}-${{ hashFiles('tests/unit/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install test requirements
        run: python -m pip install -Ur test-requirements.txt

      - name: Run pylint tests
        run: tox -epylint

  unit-tests:
    name: Unittests
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os:
          - ubuntu-16.04
        runner-python-version:
          - 3.8
    steps:

      - name: Check out ${{ github.repository }} on disk
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.runner-python-version }}

      - name: Set up pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tests/sanity/requirements.txt') }}-${{ hashFiles('tests/unit/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install test requirements
        run: python -m pip install -Ur test-requirements.txt

      - name: Run pylint tests
        run: tox -epytest

  func-tests-aws:
    name: AWS functional
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os:
          - ubuntu-16.04
        runner-python-version:
          - 3.8
    steps:

      - name: Check out ${{ github.repository }} on disk
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.runner-python-version }}

      - name: Set up pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tests/sanity/requirements.txt') }}-${{ hashFiles('tests/unit/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install packages requirements
        run: |
          sudo apt-get install -y openssh-client
          ssh-keygen -N "" -f ~/.ssh/id_rsa

      - name: Install test requirements
        run: python -m pip install -U -r requirements.txt -r test-requirements.txt

      - name: Run terraform tests
        run: tox -eterraform-aws

  func-tests-azure:
    name: Azure functional
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os:
          - ubuntu-16.04
        runner-python-version:
          - 3.8
    steps:

      - name: Check out ${{ github.repository }} on disk
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.runner-python-version }}

      - name: Set up pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tests/sanity/requirements.txt') }}-${{ hashFiles('tests/unit/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install packages requirements
        run: |
          sudo apt-get install -y openssh-client
          ssh-keygen -N "" -f ~/.ssh/id_rsa

      - name: Install test requirements
        run: python -m pip install -U -r requirements.txt -r test-requirements.txt

      - name: Run terraform tests
        run: tox -eterraform-azure
